In [59]:
import numpy as np
import pandas as pd

import scipy.stats as stats

In [43]:
# load data
mental = pd.read_csv(r'data\cleaned_mental_health_data.csv')
music = pd.read_csv(r'data\music_data_with_country_info.csv')

country_map = pd.read_csv(r'raw_data\country_mapping.csv')

In [44]:
# mental data shape and samp
print(mental.shape)
mental.head()

(292364, 20)

,Timestamp,Gender,Country,Occupation,self_employed,family_history,treatment,Days_Indoors,Growing_Stress,Changes_Habits,Mental_Health_History,Mood_Swings,Coping_Struggles,Work_Interest,Social_Weakness,mental_health_interview,care_options,Month,Season,composite_mh_score
0,2014-08-27 11:29:31,Female,United States,Corporate,Unknown,0,1,1,1.0,0.0,1.0,1,0,0.0,1.0,0.0,0.5,8,Summer,0.274544
1,2014-08-27 11:31:50,Female,United States,Corporate,Unknown,1,1,1,1.0,0.0,1.0,1,0,0.0,1.0,0.0,0.0,8,Summer,0.947969
2,2014-08-27 11:32:39,Female,United States,Corporate,Unknown,1,1,1,1.0,0.0,1.0,1,0,0.0,1.0,0.0,1.0,8,Summer,2.009174
3,2014-08-27 11:37:59,Female,United States,Corporate,No,1,1,1,1.0,0.0,1.0,1,0,0.0,1.0,0.5,1.0,8,Summer,1.732625
4,2014-08-27 11:43:36,Female,United States,Corporate,No,1,1,1,1.0,0.0,1.0,1,0,0.0,1.0,0.0,1.0,8,Summer,2.009174

In [45]:
# music data shape and samp
print(music.shape)
music.head()

(2697, 188)

,twitter-id,user-id,month,weekday,longitude,latitude,country-id,city-id,artist-id,track-id,...,Instrument_-_Electric_Guitar_(clean)-Solo,Instrument_-_Electric_Guitar_(distorted)-Solo,Instrument_-_Female_Lead_Vocals-Solo,Instrument_-_Harmonica-Solo,Instrument_-_Male_Lead_Vocals-Solo,Instrument_-_Piano-Solo,Instrument_-_Saxophone-Solo,Instrument_-_Trumpet-Solo,season,country
0,134266061230047232,314649657,11,2,-51.177275,-29.915337,0,86,343878,5986620,...,0,0,0,0,0,0,0,0,Autumn,Brazil
1,134312266639212544,329400087,11,2,-45.917521,-23.061418,0,306,78492,1403960,...,0,0,0,0,0,0,0,1,Autumn,Brazil
2,134339142418042880,105875448,11,2,-43.447310,-22.916032,0,50,393462,6800302,...,0,0,0,0,0,0,0,0,Autumn,Brazil
3,134350511678832641,108600330,11,2,-76.639496,39.304510,3,297,414087,7130125,...,0,0,0,0,0,0,0,0,Autumn,United States
4,134357350260809730,39820216,11,2,4.904054,52.354750,14,98,393462,6800302,...,0,0,0,0,0,0,0,0,Autumn,The Netherlands

In [ ]:
# filter mental data to year (2014 ONLY) and country

clean_mental = pd.DataFrame()

clean_mental['Year'] = mental.Timestamp.apply(lambda x: x[:4]).astype(int)
clean_mental['Country'] = mental.Country

clean_mental.query('Year == 2014', inplace=True)

print(clean_mental.shape)
clean_mental.head()

(277280, 2)

   Year        Country
0  2014  United States
1  2014  United States
2  2014  United States
3  2014  United States
4  2014  United States

In [46]:
# clean and filter music data for year and country
clean_music = pd.DataFrame()

clean_music['Year'] = (2013 * np.ones(music.shape[0])).astype(int)
clean_music['Country'] = (
    music['country'] # grab country column
    .replace('The Netherlands', 'Netherlands') # match country titles to those in mental set
)

clean_music.head()

   Year        Country
0  2013         Brazil
1  2013         Brazil
2  2013         Brazil
3  2013  United States
4  2013    Netherlands

In [54]:
# merge clean_music and clean_mental
clean_full = pd.concat([clean_mental, clean_music], axis=0)

clean_full.head()

   Year        Country
0  2014  United States
1  2014  United States
2  2014  United States
3  2014  United States
4  2014  United States

In [ ]:
# create crosstab table

O_table = pd.crosstab(clean_full['Year'], clean_full['Country'])
n_i = O_table.sum(axis=1)

p_table = O_table.div(n_i, axis=0)
p_table

Country,Argentina,Armenia,Australia,Barbados,Belarus,Belgium,Bolivia,Bosnia and Herzegovina,Botswana,Brazil,...,Thailand,Togo,Turkey,Ukraine,United Arab Emirates,United Kingdom,United States,Venezuela,Zambia,Zimbabwe
Year,,,,,,,,,,,,,,,,,,,,,
2013,0.001112,0.000371,0.002225,0.000371,0.002595,0.001854,0.000371,0.000000,0.000371,0.199852,...,0.000742,0.000371,0.035224,0.004079,0.000742,0.185391,0.198369,0.000742,0.000371,0.000371
2014,0.000000,0.000000,0.018920,0.000000,0.000000,0.002972,0.000000,0.001407,0.000000,0.007033,...,0.001407,0.000000,0.000000,0.000000,0.000000,0.173817,0.596401,0.000000,0.000000,0.000000

In [63]:
N = O_table.values.sum()

p_table.loc['total'] = O_table.sum(axis=0) / N

p_table

Country,Argentina,Armenia,Australia,Barbados,Belarus,Belgium,Bolivia,Bosnia and Herzegovina,Botswana,Brazil,...,Thailand,Togo,Turkey,Ukraine,United Arab Emirates,United Kingdom,United States,Venezuela,Zambia,Zimbabwe
Year,,,,,,,,,,,,,,,,,,,,,
2013,0.001112,0.000371,0.002225,0.000371,0.002595,0.001854,0.000371,0.000000,0.000371,0.199852,...,0.000742,0.000371,0.035224,0.004079,0.000742,0.185391,0.198369,0.000742,0.000371,0.000371
2014,0.000000,0.000000,0.018920,0.000000,0.000000,0.002972,0.000000,0.001407,0.000000,0.007033,...,0.001407,0.000000,0.000000,0.000000,0.000000,0.173817,0.596401,0.000000,0.000000,0.000000
total,0.000011,0.000004,0.018759,0.000004,0.000025,0.002961,0.000004,0.001393,0.000004,0.008890,...,0.001400,0.000004,0.000339,0.000039,0.000007,0.173929,0.592567,0.000007,0.000004,0.000004

Would use a hypothesis test for homogeneity. \

$H_0:$ There is no difference in the distribution of countries between 2013 and 2014. \
$H_1:$ There is a difference in the distribution of countries between 2013 and 2014.

In [64]:
p_ij, p_j = p_table.iloc[0:2], p_table.iloc[2]
T = (((p_ij - p_j)**2 / p_j).sum(axis=1) * n_i).sum()

T

np.float64(73203.52434736515)

In [65]:
r, k = O_table.shape
df = (r-1) * (k-1)

pvalue = 1 - stats.chi2.cdf(T, df)
pvalue

np.float64(0.0)

In [67]:
alpha = 0.05
pvalue < alpha

np.True_

There is sufficient evidence against the null hypothesis, so we reject thenull in favor of the alternative. That is thereis sufficient evidence to conclude that there is a difference in distribution of countries between 2013 and 2014.