In [1]:
import pandas as pd

<h2>Data Loading</h2>

Here, I loaded the 3 raw datasets that we will be using. I has also loaded the lookup tables, though they are not visible yet and will be made clearer in the data cleaning process. Below I have displayed the top 5 rows of each of the raw datasets.

In [2]:
#Importing music micro dataset, without id columns value pairs.
file_path = '/Users/shriyapattapu/Desktop/math189-proj_data/musicmicro/listening_data.txt'

music_micro_raw = pd.read_csv(
    file_path,
    sep="\t",
    header=0,
    index_col=False)

music_micro_raw.head()

,twitter-id,user-id,month,weekday,longitude,latitude,country-id,city-id,artist-id,track-id
0,134243699369590784,74717431,11,2,-50.531223,-18.453224,0,0,450514,7748381
1,134243700380401664,127821914,11,2,106.834450,-6.232960,1,1,202085,3529910
2,134243869201154048,174194590,11,2,-0.142822,51.520740,2,2,330061,5762915
3,134244034020524032,141847381,11,2,106.752390,-6.576483,1,3,404350,6987845
4,134244371557122048,87215499,11,2,-73.989890,40.738976,3,4,227460,4082536

In [3]:
#Importing raw mental health dataset.
mental_health_data_raw = pd.read_csv('Mental Health Dataset.csv')
mental_health_data_raw.head()

,Timestamp,Gender,Country,Occupation,self_employed,family_history,treatment,Days_Indoors,Growing_Stress,Changes_Habits,Mental_Health_History,Mood_Swings,Coping_Struggles,Work_Interest,Social_Weakness,mental_health_interview,care_options
0,2014-08-27 11:29:31,Female,United States,Corporate,NaN,No,Yes,1-14 days,Yes,No,Yes,Medium,No,No,Yes,No,Not sure
1,2014-08-27 11:31:50,Female,United States,Corporate,NaN,Yes,Yes,1-14 days,Yes,No,Yes,Medium,No,No,Yes,No,No
2,2014-08-27 11:32:39,Female,United States,Corporate,NaN,Yes,Yes,1-14 days,Yes,No,Yes,Medium,No,No,Yes,No,Yes
3,2014-08-27 11:37:59,Female,United States,Corporate,No,Yes,Yes,1-14 days,Yes,No,Yes,Medium,No,No,Yes,Maybe,Yes
4,2014-08-27 11:43:36,Female,United States,Corporate,No,Yes,Yes,1-14 days,Yes,No,Yes,Medium,No,No,Yes,No,Yes

In [5]:
#import autotagging dataset
import commons

tracks, tags, extra = commons.read_file('mtg/autotagging.tsv')


mtg_raw = pd.DataFrame.from_dict(tracks, orient="index")
mtg_raw.index.name = "track_id"
mtg_raw.reset_index(inplace=True)
mtg_raw.head()

ModuleNotFoundError: No module named 'commons'

<h2>Data Cleaning</h2>

In [62]:
raw_meta = pd.read_csv("../data/raw_meta.tsv", sep="\t", engine="python", on_bad_lines="skip")
raw_meta.columns = raw_meta.columns.str.lower()
raw_meta['track_id'] = raw_meta['track_id'].astype(str)
raw_meta["track_id"] = raw_meta["track_id"].str.replace("track_", "", regex=False).str.lstrip("0").astype(int)

mtg_a = pd.merge(mtg_raw, raw_meta, on="track_id", how="inner")

mtg_a.head()

,track_id,artist_id_x,album_id_x,path,duration,tags,genre,instrument,mood/theme,artist_id_y,album_id_y,track_name,artist_name,album_name,releasedate,url
0,214,14,31,14/214.mp3,124.6,[genre---punkrock],{punkrock},{},{},artist_000014,album_000031,Intro chiante,David TMX,Pouce !,2004-12-28,http://www.jamendo.com/track/214
1,215,14,31,15/215.mp3,151.4,[genre---metal],{metal},{},{},artist_000014,album_000031,Aide toi...,David TMX,Pouce !,2004-12-28,http://www.jamendo.com/track/215
2,216,14,31,16/216.mp3,234.9,[genre---metal],{metal},{},{},artist_000014,album_000031,Une charogne,David TMX,Pouce !,2004-12-28,http://www.jamendo.com/track/216
3,217,14,31,17/217.mp3,127.9,[genre---punkrock],{punkrock},{},{},artist_000014,album_000031,Aimons nous...,David TMX,Pouce !,2004-12-28,http://www.jamendo.com/track/217
4,218,14,31,18/218.mp3,180.7,[genre---punkrock],{punkrock},{},{},artist_000014,album_000031,Jouvencelle,David TMX,Pouce !,2004-12-28,http://www.jamendo.com/track/218

In [69]:
artist_map = pd.read_csv('/Users/shriyapattapu/Desktop/math189-proj_data/musicmicro/artist_mapping.txt', sep="\t", header=0, index_col=False)
track_map = pd.read_csv('/Users/shriyapattapu/Desktop/math189-proj_data/musicmicro/track_mapping.txt', sep="\t", header=0, index_col=False)

In [76]:
a = music_micro_raw.merge(artist_map, on='artist-id', how='inner')
b = a.merge(track_map, on='track-id', how='left')
b

,twitter-id,user-id,month,weekday,longitude,latitude,country-id,city-id,artist-id,track-id,artist,track
0,134243699369590784,74717431,11,2,-50.531223,-18.453224,0,0,450514,7748381,Tihuana,Na Parede do Quintal
1,134243700380401664,127821914,11,2,106.834450,-6.232960,1,1,202085,3529910,James Morrison,You give me something
2,134243869201154048,174194590,11,2,-0.142822,51.520740,2,2,330061,5762915,Pet Shop Boys,West End Girls
3,134244034020524032,141847381,11,2,106.752390,-6.576483,1,3,404350,6987845,Suede,Everything Will Flow
4,134244371557122048,87215499,11,2,-73.989890,40.738976,3,4,227460,4082536,Kaskade,Ice
...,...,...,...,...,...,...,...,...,...,...,...,...
590734,250849073052143616,134108604,9,2,-76.718850,39.955963,3,548,283679,5020296,Michael Franti & Spearhead,Say Hey
590735,250849250706092032,219099036,9,2,-111.669560,40.220425,3,5091,68747,1224442,Cartel De Santa,Traficando Rimas
590736,250849785316249600,192959967,9,2,-0.460020,51.774914,2,2700,152498,2592493,Francis Dunnery,NaN
590737,250849797165182976,226486664,9,2,106.876180,-6.275665,1,1381,375884,6536720,Secondhand Serenade,I Hate This Song
590738,250850432161820672,46547043,9,2,-117.412360,47.672800,3,2039,59333,1050122,Britney Spears,NaN